name: Essentials
main: ErosionYT\Essentials\Main
website: https://github.com/ErosionYT
author: ErosionYT
version: 1.0.0
api: 4.0.0
mcpe-protocols: [475, 476, 477, 479, 485, 486, 490, 491]

softdepend: BedrockEconomy

permissions:
  essentials.repairui.command:
    default: true
  essentials.heal.command:
    default: op
  essentials.fly.command:
    default: op
  essentials.feed.command:
    default: op
  essentials.credits.command:
    default: true
  essentials.gmc.command:
    default: op
  essentials.gms.command:
    default: op
  essentials.gmspc.command:
    default: op
  essentials.gma.command:
    default: op
  essentials.freeze.command:
    default: op
  essentials.staffchat.command:
    default: op
  essentials.speed.command:
    default: op
